# Site settings
title: Your awesome title
tagline: Simplify receiving emails in your Rails App
email: hello@thoughtbot.com
description: "Griddler is a Rails engine that provides an endpoint for the SendGrid parse api, Cloudmailin parse api, Postmark parse api or Mandrill parse api that hands off a built email object to a class implemented by you."
baseurl: ""
url: "http://thoughtbot.com"

# Build settings
markdown: kramdown
permalink: pretty
